name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
# VM build job
  build:

    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_DB: ci
          POSTGRES_USER: ci
          POSTGRES_PASSWORD: ci
        ports:
          - 5432:5432
        options: >
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install psycopg2 Dependencies
      run: |
        sudo apt-get install python-dev libpq-dev
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint Source Files
      run: |
        find . -name '*.py' -exec pylint {} \;
    - name: Create Database
      run: python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test --keepdb
